;
; File generated by cc65 v 2.19 - Git 065b0d7
;
	.fopt		compiler,"cc65 v 2.19 - Git 065b0d7"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_spawn_bullets
	.export		_update_regular_bullets
	.export		_clear_all_bullets
	.export		_enemy_killed_check
	.import		_oam_meta_spr
	.import		_i
	.import		_j
	.import		_frame_count
	.import		_pad1
	.import		_pad1_old
	.import		_player_x
	.import		_player_y
	.import		_bullets
	.import		_player_score
	.import		_bullet_sprite
	.import		_enemy_x
	.import		_enemy_y
	.import		_enemy_active
	.import		_enemy_frozen

; ---------------------------------------------------------------
; void __near__ spawn_bullets (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spawn_bullets: near

.segment	"CODE"

;
; if ((pad1 & PAD_A) && !(pad1_old & PAD_A)) {
;
	lda     _pad1
	and     #$80
	beq     L000D
	lda     _pad1_old
	and     #$80
	beq     L0010
L000D:	rts
;
; for (i = 0; i < MAX_BULLETS; ++i) {
;
L0010:	sta     _i
L000F:	lda     _i
	cmp     #$03
	bcc     L0011
;
; }
;
	rts
;
; if (!bullets[i].active) {
;
L0011:	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	bne     L0008
;
; bullets[i].active = 1;
;
	tax
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     #$01
	sta     (ptr1),y
;
; bullets[i].x = player_x + 8;
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     _player_x
	clc
	adc     #$08
	ldy     #$00
	sta     (ptr1),y
;
; bullets[i].y = player_y;
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     _player_y
	iny
	sta     (ptr1),y
;
; bullets[i].dx = 2;
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     #$02
	iny
	sta     (ptr1),y
;
; bullets[i].dy = 0;
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     #$00
	iny
	sta     (ptr1),y
;
; break;
;
	rts
;
; for (i = 0; i < MAX_BULLETS; ++i) {
;
L0008:	inc     _i
	jmp     L000F

.endproc

; ---------------------------------------------------------------
; void __near__ update_regular_bullets (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_regular_bullets: near

.segment	"CODE"

;
; for (i = 0; i < MAX_BULLETS; ++i) {
;
	lda     #$00
	sta     _i
L000D:	lda     _i
	cmp     #$03
	bcc     L0010
;
; }
;
	rts
;
; if (bullets[i].active) {
;
L0010:	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	jeq     L000F
;
; bullets[i].x += bullets[i].dx;
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	tay
	txa
	adc     #>(_bullets)
	tax
	tya
	sta     ptr2
	stx     ptr2+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     sreg
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	tay
	txa
	adc     #>(_bullets)
	tax
	tya
	ldy     #$02
	jsr     ldaidx
	clc
	adc     sreg
	ldy     #$00
	sta     (ptr2),y
;
; bullets[i].y += bullets[i].dy;
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	tay
	txa
	adc     #>(_bullets)
	tax
	tya
	sta     ptr2
	stx     ptr2+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     sreg
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	tay
	txa
	adc     #>(_bullets)
	tax
	tya
	ldy     #$03
	jsr     ldaidx
	clc
	adc     sreg
	ldy     #$01
	sta     (ptr2),y
;
; if (bullets[i].x > BULLET_RIGHT_LIMIT || bullets[i].y > 240) {
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	sta     ptr1
	txa
	clc
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #<(_bullets)
	lda     (ptr1),y
	cmp     #$FD
	bcs     L000E
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	cmp     #$F1
	bcc     L0007
;
; bullets[i].active = 0;
;
L000E:	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
;
; } else {
;
	jmp     L000F
;
; oam_meta_spr(bullets[i].x, bullets[i].y, bullet_sprite);
;
L0007:	jsr     decsp2
	ldx     #$00
	lda     _i
	jsr     mulax5
	sta     ptr1
	txa
	clc
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #<(_bullets)
	lda     (ptr1),y
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     (ptr1),y
	dey
	sta     (sp),y
	lda     #<(_bullet_sprite)
	ldx     #>(_bullet_sprite)
	jsr     _oam_meta_spr
;
; for (i = 0; i < MAX_BULLETS; ++i) {
;
L000F:	inc     _i
	jmp     L000D

.endproc

; ---------------------------------------------------------------
; void __near__ clear_all_bullets (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_all_bullets: near

.segment	"CODE"

;
; for (i = 0; i < MAX_BULLETS; ++i) {
;
	lda     #$00
	sta     _i
L0006:	lda     _i
	cmp     #$03
	bcs     L0003
;
; bullets[i].active = 0;
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
;
; for (i = 0; i < MAX_BULLETS; ++i) {
;
	inc     _i
	jmp     L0006
;
; }
;
L0003:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ enemy_killed_check (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_enemy_killed_check: near

.segment	"CODE"

;
; for (i = 0; i < MAX_BULLETS; ++i) {
;
	lda     #$00
	sta     _i
L0027:	lda     _i
	cmp     #$03
	bcc     L0031
;
; }
;
	rts
;
; if (i % 2 != (frame_count % 2)) continue; // skip this bullet this frame
;
L0031:	and     #$01
	sta     ptr1
	lda     _frame_count
	and     #$01
	cmp     ptr1
	jne     L0030
;
; if (bullets[i].active) {
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	jeq     L0030
;
; for (j = 0; j < MAX_ENEMIES; ++j) {
;
	lda     #$00
	sta     _j
L0028:	lda     _j
	cmp     #$06
	jcs     L0030
;
; if (enemy_active[j] && enemy_x[j] <= 240) {
;
	ldy     _j
	lda     _enemy_active,y
	jeq     L002F
	ldy     _j
	lda     _enemy_x,y
	cmp     #$F1
	jcs     L002F
;
; if ((bullets[i].x > enemy_x[j] ? bullets[i].x - enemy_x[j] : enemy_x[j] - bullets[i].x) < 6 &&
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	sta     ptr1
	txa
	clc
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #<(_bullets)
	lda     (ptr1),y
	ldy     _j
	cmp     _enemy_x,y
	bcc     L0014
	beq     L0014
	ldx     #$00
	lda     _i
	jsr     mulax5
	sta     ptr1
	txa
	clc
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #<(_bullets)
	lda     (ptr1),y
	sec
	ldy     _j
	sbc     _enemy_x,y
	ldx     #$00
	bcs     L0016
	dex
	jmp     L0016
L0014:	ldy     _j
	lda     _enemy_x,y
	jsr     pusha0
	lda     _i
	jsr     mulax5
	sta     ptr1
	txa
	clc
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #<(_bullets)
	lda     (ptr1),y
	jsr     tossuba0
L0016:	cmp     #$06
	txa
	sbc     #$00
	bvc     L0018
	eor     #$80
L0018:	jpl     L002F
;
; (bullets[i].y > enemy_y[j] ? bullets[i].y - enemy_y[j] : enemy_y[j] - bullets[i].y) < 6) {
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	ldy     _j
	cmp     _enemy_y,y
	bcc     L001B
	beq     L001B
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sec
	ldy     _j
	sbc     _enemy_y,y
	ldx     #$00
	bcs     L001D
	dex
	jmp     L001D
L001B:	ldy     _j
	lda     _enemy_y,y
	jsr     pusha0
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     tossuba0
L001D:	cmp     #$06
	txa
	sbc     #$00
	bvc     L001F
	eor     #$80
L001F:	bpl     L002F
;
; bullets[i].active = 0;
;
	ldx     #$00
	lda     _i
	jsr     mulax5
	clc
	adc     #<(_bullets)
	sta     ptr1
	txa
	adc     #>(_bullets)
	sta     ptr1+1
	lda     #$00
	ldy     #$04
	sta     (ptr1),y
;
; enemy_active[j] = 0;
;
	ldy     _j
	sta     _enemy_active,y
;
; enemy_frozen[j] = 0;
;
	sta     _enemy_frozen,y
;
; player_score += 10;
;
	lda     #$0A
	clc
	adc     _player_score
	sta     _player_score
	bcc     L0030
	inc     _player_score+1
;
; break;
;
	jmp     L0030
;
; for (j = 0; j < MAX_ENEMIES; ++j) {
;
L002F:	inc     _j
	jmp     L0028
;
; for (i = 0; i < MAX_BULLETS; ++i) {
;
L0030:	inc     _i
	jmp     L0027

.endproc

