;
; File generated by cc65 v 2.19 - Git 065b0d7
;
	.fopt		compiler,"cc65 v 2.19 - Git 065b0d7"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_typewriter_char
	.export		_briefing_lines
	.export		_zarnella_lv1_start
	.export		_luma_lv1_start
	.export		_bubbles_lv1_start
	.export		_zarnella_lv1_end
	.export		_luma_lv1_end
	.export		_bubbles_lv1_end
	.export		_zarnella_lv2_start
	.export		_luma_lv2_start
	.export		_bubbles_lv2_start
	.export		_zarnella_lv2_end
	.export		_luma_lv2_end
	.export		_bubbles_lv2_end
	.export		_zarnella_lv3_start
	.export		_luma_lv3_start
	.export		_bubbles_lv3_start
	.export		_zarnella_lv3_end
	.export		_luma_lv3_end
	.export		_bubbles_lv3_end
	.export		_zarnella_boss_start
	.export		_luma_boss_start
	.export		_bubbles_boss_start
	.export		_zarnella_boss_end
	.export		_luma_boss_end
	.export		_bubbles_boss_end
	.export		_zarnella_romance
	.export		_luma_romance
	.export		_bubbles_romance
	.export		_lonely_ending
	.export		_gameover_early
	.export		_gameover_mid
	.export		_gameover_late
	.export		_show_typewriter
	.export		_typewriter_reset
	.export		_mission_begin_text
	.export		_mission_end_text
	.export		_show_romance_ending
	.export		_show_game_over_screen
	.import		_one_vram_buffer
	.import		_multi_vram_buffer_horz
	.import		_current_level
	.import		_selected_crewmate
	.import		_player_score
	.import		_score_string
	.import		_typewriter_step
	.import		_typewriter_line
	.import		_typewriter_ended
	.import		_total_romance_score
	.import		_get_romance_winner
	.import		_update_score_string
	.export		_typewriter_delay

.segment	"DATA"

_typewriter_char:
	.byte	$00
_typewriter_delay:
	.byte	$00

.segment	"RODATA"

_briefing_lines:
	.addr	S0001
	.byte	$02
	.byte	$02
	.addr	S0002
	.byte	$04
	.byte	$05
	.addr	S0003
	.byte	$03
	.byte	$07
	.addr	S0004
	.byte	$01
	.byte	$0A
	.addr	S0005
	.byte	$01
	.byte	$0C
	.addr	S0006
	.byte	$01
	.byte	$0F
	.addr	S0007
	.byte	$01
	.byte	$11
	.addr	S0008
	.byte	$01
	.byte	$16
_zarnella_lv1_start:
	.addr	S0009
	.byte	$02
	.byte	$0B
	.addr	S000A
	.byte	$06
	.byte	$0F
	.addr	S000B
	.byte	$03
	.byte	$11
	.addr	S000C
	.byte	$00
	.byte	$13
_luma_lv1_start:
	.addr	S000D
	.byte	$02
	.byte	$0B
	.addr	S000E
	.byte	$04
	.byte	$0F
	.addr	S000F
	.byte	$03
	.byte	$11
	.addr	S0010
	.byte	$00
	.byte	$13
_bubbles_lv1_start:
	.addr	S0011
	.byte	$02
	.byte	$0B
	.addr	S0012
	.byte	$06
	.byte	$0F
	.addr	S0013
	.byte	$00
	.byte	$11
_zarnella_lv1_end:
	.addr	S0014
	.byte	$02
	.byte	$0B
	.addr	S0015
	.byte	$05
	.byte	$0F
	.addr	S0016
	.byte	$00
	.byte	$11
_luma_lv1_end:
	.addr	S0017
	.byte	$03
	.byte	$0B
	.addr	S0018
	.byte	$05
	.byte	$0F
	.addr	S0019
	.byte	$00
	.byte	$11
_bubbles_lv1_end:
	.addr	S001A
	.byte	$04
	.byte	$0B
	.addr	S001B
	.byte	$0B
	.byte	$0F
	.addr	S001C
	.byte	$00
	.byte	$11
_zarnella_lv2_start:
	.addr	S001D
	.byte	$01
	.byte	$0B
	.addr	S001E
	.byte	$02
	.byte	$0D
	.addr	S001F
	.byte	$00
	.byte	$0F
	.addr	S0020
	.byte	$0A
	.byte	$11
	.addr	S0021
	.byte	$06
	.byte	$13
	.addr	S0022
	.byte	$00
	.byte	$0F
_luma_lv2_start:
	.addr	S0023
	.byte	$01
	.byte	$0B
	.addr	S0024
	.byte	$01
	.byte	$0D
	.addr	S0025
	.byte	$00
	.byte	$0F
	.addr	S0026
	.byte	$09
	.byte	$11
	.addr	S0027
	.byte	$04
	.byte	$13
	.addr	S0028
	.byte	$00
	.byte	$0F
_bubbles_lv2_start:
	.addr	S0029
	.byte	$02
	.byte	$0B
	.addr	S002A
	.byte	$02
	.byte	$0D
	.addr	S002B
	.byte	$00
	.byte	$11
	.addr	S002C
	.byte	$09
	.byte	$0F
	.addr	S002D
	.byte	$00
	.byte	$11
	.addr	S002E
	.byte	$02
	.byte	$13
	.addr	S002F
	.byte	$00
	.byte	$11
_zarnella_lv2_end:
	.addr	S0030
	.byte	$05
	.byte	$0B
	.addr	S0031
	.byte	$07
	.byte	$0D
	.addr	S0032
	.byte	$05
	.byte	$0F
	.addr	S0033
	.byte	$00
	.byte	$11
	.addr	S0034
	.byte	$07
	.byte	$13
	.addr	S0035
	.byte	$00
	.byte	$11
_luma_lv2_end:
	.addr	S0036
	.byte	$08
	.byte	$0A
	.addr	S0037
	.byte	$08
	.byte	$0C
	.addr	S0038
	.byte	$08
	.byte	$0E
	.addr	S0039
	.byte	$00
	.byte	$10
	.addr	S003A
	.byte	$06
	.byte	$12
	.addr	S003B
	.byte	$00
	.byte	$10
	.addr	S003C
	.byte	$0B
	.byte	$14
	.addr	S003D
	.byte	$00
	.byte	$10
_bubbles_lv2_end:
	.addr	S003E
	.byte	$07
	.byte	$0B
	.addr	S003F
	.byte	$0A
	.byte	$0D
	.addr	S0040
	.byte	$06
	.byte	$0F
	.addr	S0041
	.byte	$00
	.byte	$11
	.addr	S0042
	.byte	$01
	.byte	$13
	.addr	S0043
	.byte	$00
	.byte	$11
_zarnella_lv3_start:
	.addr	S0044
	.byte	$08
	.byte	$0B
	.addr	S0045
	.byte	$09
	.byte	$0D
	.addr	S0046
	.byte	$07
	.byte	$0F
	.addr	S0047
	.byte	$00
	.byte	$11
	.addr	S0048
	.byte	$02
	.byte	$13
	.addr	S0049
	.byte	$00
	.byte	$11
	.addr	S004A
	.byte	$15
	.byte	$13
	.addr	S004B
	.byte	$00
	.byte	$11
_luma_lv3_start:
	.addr	S004C
	.byte	$03
	.byte	$0B
	.addr	S004D
	.byte	$06
	.byte	$0D
	.addr	S004E
	.byte	$02
	.byte	$0F
	.addr	S004F
	.byte	$07
	.byte	$11
	.addr	S0050
	.byte	$00
	.byte	$13
_bubbles_lv3_start:
	.addr	S0051
	.byte	$04
	.byte	$0B
	.addr	S0052
	.byte	$05
	.byte	$0D
	.addr	S0053
	.byte	$00
	.byte	$0F
	.addr	S0054
	.byte	$03
	.byte	$11
	.addr	S0055
	.byte	$00
	.byte	$0F
_zarnella_lv3_end:
	.addr	S0056
	.byte	$01
	.byte	$0A
	.addr	S0057
	.byte	$00
	.byte	$10
	.addr	S0058
	.byte	$09
	.byte	$0C
	.addr	S0059
	.byte	$00
	.byte	$10
	.addr	S005A
	.byte	$10
	.byte	$0C
	.addr	S005B
	.byte	$00
	.byte	$10
	.addr	S005C
	.byte	$05
	.byte	$0E
	.addr	S005D
	.byte	$00
	.byte	$10
	.addr	S005E
	.byte	$06
	.byte	$12
	.addr	S005F
	.byte	$08
	.byte	$14
	.addr	S0060
	.byte	$00
	.byte	$10
_luma_lv3_end:
	.addr	S0061
	.byte	$01
	.byte	$0B
	.addr	S0062
	.byte	$00
	.byte	$0F
	.addr	S0063
	.byte	$0B
	.byte	$0B
	.addr	S0064
	.byte	$00
	.byte	$0F
	.addr	S0065
	.byte	$02
	.byte	$0D
	.addr	S0066
	.byte	$00
	.byte	$0F
	.addr	S0067
	.byte	$0D
	.byte	$0D
	.addr	S0068
	.byte	$00
	.byte	$0F
	.addr	S0069
	.byte	$01
	.byte	$11
	.addr	S006A
	.byte	$00
	.byte	$0F
	.addr	S006B
	.byte	$0D
	.byte	$11
	.addr	S006C
	.byte	$00
	.byte	$0F
_bubbles_lv3_end:
	.addr	S006D
	.byte	$01
	.byte	$0B
	.addr	S006E
	.byte	$00
	.byte	$0F
	.addr	S006F
	.byte	$14
	.byte	$0B
	.addr	S0070
	.byte	$00
	.byte	$0F
	.addr	S0071
	.byte	$02
	.byte	$0D
	.addr	S0072
	.byte	$00
	.byte	$0F
	.addr	S0073
	.byte	$04
	.byte	$11
	.addr	S0074
	.byte	$00
	.byte	$0F
	.addr	S0075
	.byte	$0A
	.byte	$13
	.addr	S0076
	.byte	$00
	.byte	$0F
_zarnella_boss_start:
	.addr	S0077
	.byte	$0B
	.byte	$09
	.addr	S0078
	.byte	$00
	.byte	$0D
	.addr	S0079
	.byte	$06
	.byte	$0B
	.addr	S007A
	.byte	$00
	.byte	$0D
	.addr	S007B
	.byte	$07
	.byte	$0F
	.addr	S007C
	.byte	$07
	.byte	$11
	.addr	S007D
	.byte	$00
	.byte	$0D
	.addr	S007E
	.byte	$02
	.byte	$14
	.addr	S007F
	.byte	$00
	.byte	$0D
_luma_boss_start:
	.addr	S0080
	.byte	$02
	.byte	$0B
	.addr	S0081
	.byte	$00
	.byte	$0F
	.addr	S0082
	.byte	$01
	.byte	$0D
	.addr	S0083
	.byte	$00
	.byte	$0F
	.addr	S0084
	.byte	$17
	.byte	$0D
	.addr	S0085
	.byte	$00
	.byte	$0F
	.addr	S0086
	.byte	$04
	.byte	$11
	.addr	S0087
	.byte	$05
	.byte	$13
	.addr	S0088
	.byte	$00
	.byte	$0F
_bubbles_boss_start:
	.addr	S0089
	.byte	$06
	.byte	$09
	.addr	S008A
	.byte	$08
	.byte	$0B
	.addr	S008B
	.byte	$00
	.byte	$0D
	.addr	S008C
	.byte	$06
	.byte	$0F
	.addr	S008D
	.byte	$00
	.byte	$0D
	.addr	S008E
	.byte	$13
	.byte	$0F
	.addr	S008F
	.byte	$00
	.byte	$0D
	.addr	S0090
	.byte	$08
	.byte	$11
	.addr	S0091
	.byte	$00
	.byte	$0D
	.addr	S0092
	.byte	$03
	.byte	$15
	.addr	S0093
	.byte	$00
	.byte	$0D
_zarnella_boss_end:
	.addr	S0094
	.byte	$02
	.byte	$0B
	.addr	S0095
	.byte	$00
	.byte	$0F
	.addr	S0096
	.byte	$03
	.byte	$0D
	.addr	S0097
	.byte	$00
	.byte	$0F
	.addr	S0098
	.byte	$07
	.byte	$11
	.addr	S0099
	.byte	$05
	.byte	$13
	.addr	S009A
	.byte	$00
	.byte	$0F
_luma_boss_end:
	.addr	S009B
	.byte	$04
	.byte	$0B
	.addr	S009C
	.byte	$00
	.byte	$0F
	.addr	S009D
	.byte	$0C
	.byte	$0B
	.addr	S009E
	.byte	$0B
	.byte	$0D
	.addr	S009F
	.byte	$00
	.byte	$0F
	.addr	S00A0
	.byte	$05
	.byte	$11
	.addr	S00A1
	.byte	$00
	.byte	$0F
	.addr	S00A2
	.byte	$10
	.byte	$11
	.addr	S00A3
	.byte	$00
	.byte	$0F
	.addr	S00A4
	.byte	$02
	.byte	$13
	.addr	S00A5
	.byte	$00
	.byte	$0F
	.addr	S00A6
	.byte	$06
	.byte	$13
	.addr	S00A7
	.byte	$00
	.byte	$0F
_bubbles_boss_end:
	.addr	S00A8
	.byte	$03
	.byte	$09
	.addr	S00A9
	.byte	$06
	.byte	$0B
	.addr	S00AA
	.byte	$00
	.byte	$0D
	.addr	S00AB
	.byte	$05
	.byte	$0F
	.addr	S00AC
	.byte	$09
	.byte	$11
	.addr	S00AD
	.byte	$00
	.byte	$0D
	.addr	S00AE
	.byte	$08
	.byte	$15
	.addr	S00AF
	.byte	$00
	.byte	$0D
_zarnella_romance:
	.addr	S00B0
	.byte	$03
	.byte	$09
	.addr	S00B1
	.byte	$00
	.byte	$0D
	.addr	S00B2
	.byte	$01
	.byte	$0B
	.addr	S00B3
	.byte	$00
	.byte	$0D
	.addr	S00B4
	.byte	$01
	.byte	$0F
	.addr	S00B5
	.byte	$00
	.byte	$0D
	.addr	S00B6
	.byte	$05
	.byte	$11
	.addr	S00B7
	.byte	$00
	.byte	$0D
	.addr	S00B8
	.byte	$0A
	.byte	$13
	.addr	S00B9
	.byte	$00
	.byte	$0D
_luma_romance:
	.addr	S00BA
	.byte	$04
	.byte	$09
	.addr	S00BB
	.byte	$00
	.byte	$0D
	.addr	S00BC
	.byte	$02
	.byte	$0B
	.addr	S00BD
	.byte	$00
	.byte	$0D
	.addr	S00BE
	.byte	$0E
	.byte	$0B
	.addr	S00BF
	.byte	$00
	.byte	$0D
	.addr	S00C0
	.byte	$08
	.byte	$0F
	.addr	S00C1
	.byte	$07
	.byte	$11
	.addr	S00C2
	.byte	$00
	.byte	$0D
	.addr	S00C3
	.byte	$03
	.byte	$13
	.addr	S00C4
	.byte	$00
	.byte	$0D
	.addr	S00C5
	.byte	$0C
	.byte	$13
	.addr	S00C6
	.byte	$00
	.byte	$0D
	.addr	S00C7
	.byte	$03
	.byte	$15
	.addr	S00C8
	.byte	$00
	.byte	$0D
	.addr	S00C9
	.byte	$0A
	.byte	$15
	.addr	S00CA
	.byte	$00
	.byte	$0D
_bubbles_romance:
	.addr	S00CB
	.byte	$02
	.byte	$09
	.addr	S00CC
	.byte	$00
	.byte	$11
	.addr	S00CD
	.byte	$06
	.byte	$0B
	.addr	S00CE
	.byte	$00
	.byte	$11
	.addr	S00CF
	.byte	$04
	.byte	$0D
	.addr	S00D0
	.byte	$00
	.byte	$11
	.addr	S00D1
	.byte	$03
	.byte	$0F
	.addr	S00D2
	.byte	$00
	.byte	$11
	.addr	S00D3
	.byte	$09
	.byte	$13
	.addr	S00D4
	.byte	$00
	.byte	$11
	.addr	S00D5
	.byte	$03
	.byte	$15
	.addr	S00D6
	.byte	$00
	.byte	$11
_lonely_ending:
	.addr	S00D7
	.byte	$02
	.byte	$05
	.addr	S00D8
	.byte	$00
	.byte	$03
	.addr	S00D9
	.byte	$06
	.byte	$09
	.addr	S00DA
	.byte	$00
	.byte	$03
	.addr	S00DB
	.byte	$0F
	.byte	$09
	.addr	S00DC
	.byte	$00
	.byte	$03
	.addr	S00DD
	.byte	$0C
	.byte	$0D
	.addr	S00DE
	.byte	$00
	.byte	$03
	.addr	S00DF
	.byte	$01
	.byte	$0F
	.addr	S00E0
	.byte	$00
	.byte	$03
	.addr	S00E1
	.byte	$01
	.byte	$13
	.addr	S00E2
	.byte	$00
	.byte	$03
_gameover_early:
	.addr	S00E3
	.byte	$09
	.byte	$06
	.addr	S00E4
	.byte	$00
	.byte	$15
	.addr	S00E5
	.byte	$08
	.byte	$0A
	.addr	S00E6
	.byte	$00
	.byte	$15
	.addr	S00E7
	.byte	$02
	.byte	$0C
	.addr	S00E8
	.byte	$00
	.byte	$15
	.addr	S00E9
	.byte	$06
	.byte	$10
	.addr	S00EA
	.byte	$00
	.byte	$15
	.addr	S00EB
	.byte	$0B
	.byte	$14
	.addr	S00EC
	.byte	$00
	.byte	$15
_gameover_mid:
	.addr	S00ED
	.byte	$05
	.byte	$06
	.addr	S00EE
	.byte	$00
	.byte	$14
	.addr	S00EF
	.byte	$11
	.byte	$06
	.addr	S00F0
	.byte	$00
	.byte	$14
	.addr	S00F1
	.byte	$03
	.byte	$0A
	.addr	S00F2
	.byte	$05
	.byte	$0C
	.addr	S00F3
	.byte	$00
	.byte	$14
	.addr	S00F4
	.byte	$08
	.byte	$10
	.addr	S00F5
	.byte	$07
	.byte	$12
	.addr	S00F6
	.byte	$00
	.byte	$14
_gameover_late:
	.addr	S00F7
	.byte	$0B
	.byte	$03
	.addr	S00F8
	.byte	$07
	.byte	$05
	.addr	S00F9
	.byte	$00
	.byte	$07
	.addr	S00FA
	.byte	$04
	.byte	$09
	.addr	S00FB
	.byte	$0B
	.byte	$0B
	.addr	S00FC
	.byte	$00
	.byte	$07
	.addr	S00FD
	.byte	$04
	.byte	$0F
	.addr	S00FE
	.byte	$00
	.byte	$07
	.addr	S00FF
	.byte	$09
	.byte	$13
	.addr	S0100
	.byte	$00
	.byte	$07
	.addr	S0101
	.byte	$14
	.byte	$13
	.addr	S0102
	.byte	$00
	.byte	$07
	.addr	S0103
	.byte	$04
	.byte	$17
	.addr	S0104
	.byte	$00
	.byte	$07
S0004:
	.byte	$4F,$55,$54,$50,$4F,$53,$54,$20,$44,$45,$4C,$54,$41,$2D,$5A,$55
	.byte	$4C,$55,$2D,$37,$20,$57,$45,$4E,$54,$20,$44,$41,$52,$4B,$2E,$00
S00B4:
	.byte	$2E,$2E,$2E,$46,$49,$4E,$45,$2E,$20,$49,$20,$2A,$4C,$49,$4B,$45
	.byte	$2A,$20,$59,$4F,$55,$2C,$20,$4D,$45,$41,$54,$42,$41,$47,$2E,$00
S0042:
	.byte	$49,$27,$4D,$20,$47,$4F,$4E,$4E,$41,$20,$50,$4F,$50,$20,$46,$52
	.byte	$4F,$4D,$20,$45,$58,$43,$49,$54,$45,$4D,$45,$4E,$54,$21,$00
S0005:
	.byte	$50,$4F,$53,$53,$49,$42,$4C,$45,$20,$41,$49,$20,$47,$4F,$4E,$45
	.byte	$20,$52,$4F,$47,$55,$45,$2E,$20,$41,$47,$41,$49,$4E,$2E,$00
S0006:
	.byte	$47,$4F,$20,$49,$4E,$20,$48,$41,$52,$44,$20,$41,$4E,$44,$20,$46
	.byte	$49,$4E,$44,$20,$54,$48,$45,$20,$54,$52,$55,$54,$48,$2E,$00
S0007:
	.byte	$45,$58,$50,$4C,$4F,$53,$49,$4F,$4E,$53,$20,$4F,$50,$54,$49,$4F
	.byte	$4E,$41,$4C,$20,$42,$55,$54,$20,$4C,$49,$4B,$45,$4C,$59,$00
S0008:
	.byte	$59,$4F,$55,$27,$52,$45,$20,$4F,$55,$52,$20,$4F,$4E,$4C,$59,$20
	.byte	$48,$4F,$50,$45,$2E,$20,$53,$4F,$52,$54,$20,$4F,$46,$2E,$00
S00B2:
	.byte	$49,$20,$44,$49,$44,$4E,$27,$54,$20,$48,$41,$54,$45,$20,$57,$4F
	.byte	$52,$4B,$49,$4E,$47,$20,$57,$49,$54,$48,$20,$59,$4F,$55,$00
S00DF:
	.byte	$46,$4C,$4F,$41,$54,$49,$4E,$47,$20,$41,$4C,$4F,$4E,$45,$20,$41
	.byte	$4D,$4F,$4E,$47,$20,$54,$48,$45,$20,$53,$54,$41,$52,$53,$00
S00E1:
	.byte	$42,$45,$54,$54,$45,$52,$20,$4C,$55,$43,$4B,$20,$4E,$45,$58,$54
	.byte	$20,$54,$49,$4D,$45,$2C,$20,$43,$41,$50,$54,$41,$49,$4E,$00
S0056:
	.byte	$54,$48,$49,$53,$20,$46,$49,$47,$48,$54,$20,$57,$41,$53,$20,$41
	.byte	$4C,$4D,$4F,$53,$54,$20,$57,$4F,$52,$54,$48,$20,$49,$54,$00
S00F6:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$00
S00F3	:=	S00F6+0
S00F0	:=	S00F6+0
S0010	:=	S00F6+0
S00EC	:=	S00F6+0
S00EA	:=	S00F6+0
S0013	:=	S00F6+0
S0014:
	.byte	$57,$45,$4C,$4C,$2C,$20,$54,$48,$41,$54,$20,$57,$41,$53,$4E,$27
	.byte	$54,$20,$2A,$54,$45,$52,$52,$49,$42,$4C,$45,$2A,$2E,$00
S00E8	:=	S00F6+0
S0016	:=	S00F6+0
S00E7:
	.byte	$54,$48,$45,$20,$45,$4E,$45,$4D,$59,$20,$44,$49,$44,$4E,$27,$54
	.byte	$20,$45,$56,$45,$4E,$20,$4E,$4F,$54,$49,$43,$45,$2E,$00
S00E4	:=	S00F6+0
S0019	:=	S00F6+0
S00E2	:=	S00F6+0
S00F9	:=	S00F6+0
S001C	:=	S00F6+0
S001D:
	.byte	$54,$48,$45,$59,$20,$53,$45,$4E,$54,$20,$4D,$45,$20,$2A,$42,$41
	.byte	$43,$4B,$2A,$20,$57,$49,$54,$48,$20,$59,$4F,$55,$3F,$00
S00E0	:=	S00F6+0
S001F	:=	S00F6+0
S00FC	:=	S00F6+0
S00DE	:=	S00F6+0
S0022	:=	S00F6+0
S0023:
	.byte	$4C,$41,$53,$54,$20,$54,$45,$41,$4D,$2D,$55,$50,$3A,$20,$45,$46
	.byte	$46,$49,$43,$49,$45,$4E,$43,$59,$20,$4C,$4F,$53,$53,$00
S0024:
	.byte	$4D,$49,$54,$49,$47,$41,$54,$49,$4E,$47,$20,$48,$55,$4D,$41,$4E
	.byte	$20,$56,$41,$52,$49,$41,$42,$4C,$45,$53,$2E,$2E,$2E,$00
S0025	:=	S00F6+0
S00DC	:=	S00F6+0
S00D8	:=	S00F6+0
S0028	:=	S00F6+0
S00D6	:=	S00F6+0
S00D2	:=	S00F6+0
S002B	:=	S00F6+0
S00CC	:=	S00F6+0
S002D	:=	S00F6+0
S00CB:
	.byte	$57,$55,$42,$42,$4C,$45,$20,$57,$55,$42,$42,$4C,$45,$21,$20,$59
	.byte	$4F,$55,$20,$50,$49,$43,$4B,$45,$44,$20,$4D,$45,$21,$00
S002F	:=	S00F6+0
S00CA	:=	S00F6+0
S00C6	:=	S00F6+0
S00C2	:=	S00F6+0
S0033	:=	S00F6+0
S00BF	:=	S00F6+0
S0035	:=	S00F6+0
S00BB	:=	S00F6+0
S00B9	:=	S00F6+0
S00B5	:=	S00F6+0
S0039	:=	S00F6+0
S00FE	:=	S00F6+0
S003B	:=	S00F6+0
S00B3	:=	S00F6+0
S003D	:=	S00F6+0
S0102	:=	S00F6+0
S00AF	:=	S00F6+0
S00AD	:=	S00F6+0
S0041	:=	S00F6+0
S0104	:=	S00F6+0
S0043	:=	S00F6+0
S00AA	:=	S00F6+0
S00A7	:=	S00F6+0
S00A3	:=	S00F6+0
S0047	:=	S00F6+0
S009F	:=	S00F6+0
S0049	:=	S00F6+0
S009A	:=	S00F6+0
S004B	:=	S00F6+0
S0097	:=	S00F6+0
S0093	:=	S00F6+0
S0091	:=	S00F6+0
S008F	:=	S00F6+0
S0050	:=	S00F6+0
S008D	:=	S00F6+0
S008B	:=	S00F6+0
S0053	:=	S00F6+0
S0088	:=	S00F6+0
S0055	:=	S00F6+0
S000C	:=	S00F6+0
S0057	:=	S00F6+0
S0085	:=	S00F6+0
S0081	:=	S00F6+0
S007F	:=	S00F6+0
S007E:
	.byte	$4A,$55,$53,$54,$20,$54,$52,$59,$20,$54,$4F,$20,$4B,$45,$45,$50
	.byte	$20,$55,$50,$2C,$20,$43,$41,$50,$54,$41,$49,$4E,$2E,$00
S007D	:=	S00F6+0
S005D	:=	S00F6+0
S007A	:=	S00F6+0
S0076	:=	S00F6+0
S0060	:=	S00F6+0
S0074	:=	S00F6+0
S0072	:=	S00F6+0
S0070	:=	S00F6+0
S0064	:=	S00F6+0
S006E	:=	S00F6+0
S006C	:=	S00F6+0
S006A	:=	S00F6+0
S0068	:=	S00F6+0
S0001:
	.byte	$47,$41,$4C,$41,$43,$54,$49,$43,$20,$43,$4F,$4D,$4D,$41,$4E,$44
	.byte	$20,$42,$4F,$4F,$54,$49,$4E,$47,$20,$55,$50,$2E,$2E,$00
S004E:
	.byte	$4C,$45,$54,$27,$53,$20,$46,$49,$4E,$49,$53,$48,$20,$54,$48,$49
	.byte	$53,$20,$42,$45,$46,$4F,$52,$45,$20,$59,$4F,$55,$00
S0094:
	.byte	$48,$41,$48,$21,$20,$4E,$4F,$57,$20,$2A,$54,$48,$41,$54,$2A,$20
	.byte	$57,$41,$53,$20,$41,$20,$46,$49,$47,$48,$54,$2E,$00
S0011:
	.byte	$57,$55,$42,$42,$4C,$45,$20,$57,$55,$42,$42,$4C,$45,$20,$57,$55
	.byte	$42,$42,$4C,$45,$20,$57,$55,$42,$42,$4C,$45,$21,$00
S0009:
	.byte	$44,$4F,$4E,$27,$54,$20,$53,$4C,$4F,$57,$20,$4D,$45,$20,$44,$4F
	.byte	$57,$4E,$2C,$20,$4D,$45,$41,$54,$42,$41,$47,$2E,$00
S001E:
	.byte	$45,$49,$54,$48,$45,$52,$20,$49,$27,$4D,$20,$42,$45,$49,$4E,$47
	.byte	$20,$50,$55,$4E,$49,$53,$48,$45,$44,$2E,$2E,$2E,$00
S00D7:
	.byte	$59,$4F,$55,$52,$20,$43,$52,$45,$57,$20,$57,$45,$4E,$54,$20,$54
	.byte	$48,$45,$49,$52,$20,$4F,$57,$4E,$20,$57,$41,$59,$00
S002E:
	.byte	$4C,$45,$54,$27,$53,$20,$4D,$41,$4B,$45,$20,$54,$48,$45,$20,$44
	.byte	$52,$45,$41,$4D,$20,$2A,$52,$45,$41,$4C,$2A,$2E,$00
S0080:
	.byte	$41,$4C,$4C,$20,$50,$41,$54,$48,$53,$20,$4C,$45,$41,$44,$20,$54
	.byte	$4F,$20,$54,$48,$49,$53,$20,$50,$4F,$49,$4E,$54,$00
S002A:
	.byte	$54,$48,$45,$52,$45,$20,$57,$41,$53,$20,$53,$4C,$49,$4D,$45,$20
	.byte	$45,$56,$45,$52,$59,$57,$48,$45,$52,$45,$2E,$00
S00D1:
	.byte	$49,$27,$4C,$4C,$20,$53,$54,$49,$43,$4B,$20,$54,$4F,$20,$59,$4F
	.byte	$55,$20,$4C,$49,$4B,$45,$20,$47,$4C,$55,$45,$00
S0029:
	.byte	$4C,$41,$53,$54,$20,$4E,$49,$47,$48,$54,$20,$49,$20,$44,$52,$45
	.byte	$41,$4D,$54,$20,$4F,$46,$20,$59,$4F,$55,$2E,$00
S0017:
	.byte	$4D,$49,$53,$53,$49,$4F,$4E,$20,$50,$41,$52,$41,$4D,$45,$54,$45
	.byte	$52,$53,$20,$43,$4F,$4D,$50,$4C,$45,$54,$45,$00
S000D:
	.byte	$55,$50,$4C,$4F,$41,$44,$49,$4E,$47,$20,$4D,$49,$53,$53,$49,$4F
	.byte	$4E,$20,$50,$52,$4F,$54,$4F,$43,$4F,$4C,$53,$00
S0003:
	.byte	$4F,$52,$20,$41,$54,$20,$4C,$45,$41,$53,$54,$20,$53,$4F,$4D,$45
	.byte	$4F,$4E,$45,$20,$53,$48,$4F,$4F,$54,$59,$2E,$00
S004C:
	.byte	$53,$59,$53,$54,$45,$4D,$20,$53,$54,$41,$42,$49,$4C,$49,$54,$59
	.byte	$3A,$20,$43,$52,$49,$54,$49,$43,$41,$4C,$2E,$00
S0092:
	.byte	$4C,$45,$54,$27,$53,$20,$47,$4F,$20,$42,$55,$52,$53,$54,$20,$49
	.byte	$54,$2C,$20,$43,$41,$50,$54,$41,$49,$4E,$21,$00
S0071:
	.byte	$45,$56,$45,$52,$59,$20,$42,$4C,$41,$53,$54,$20,$4D,$41,$44,$45
	.byte	$20,$4D,$45,$20,$51,$55,$49,$56,$45,$52,$21,$00
S00B0:
	.byte	$4C,$4F,$4F,$4B,$2C,$20,$44,$4F,$4E,$27,$54,$20,$4D,$41,$4B,$45
	.byte	$20,$4D,$45,$20,$53,$41,$59,$20,$49,$54,$00
S0054:
	.byte	$41,$4E,$44,$20,$54,$48,$45,$59,$20,$44,$45,$4D,$41,$4E,$44,$20
	.byte	$53,$41,$43,$52,$49,$46,$49,$43,$45,$2E,$00
S00F1:
	.byte	$59,$4F,$55,$52,$20,$43,$52,$45,$57,$4D,$41,$54,$45,$20,$4E,$45
	.byte	$56,$45,$52,$20,$47,$4F,$54,$20,$54,$4F,$00
S000B:
	.byte	$49,$27,$4C,$4C,$20,$48,$41,$55,$4E,$54,$20,$59,$4F,$55,$20,$50
	.byte	$45,$52,$53,$4F,$4E,$41,$4C,$4C,$59,$2E,$00
S001A:
	.byte	$42,$55,$42,$42,$4C,$45,$20,$4D,$49,$53,$53,$49,$4F,$4E,$20,$53
	.byte	$55,$43,$43,$45,$53,$53,$46,$55,$4C,$00
S000F:
	.byte	$4C,$45,$54,$27,$53,$20,$4D,$41,$4B,$45,$20,$54,$48,$49,$53,$20
	.byte	$45,$46,$46,$49,$43,$49,$45,$4E,$54,$00
S0103:
	.byte	$4C,$4F,$56,$45,$20,$4E,$45,$56,$45,$52,$20,$53,$54,$4F,$4F,$44
	.byte	$20,$41,$20,$43,$48,$41,$4E,$43,$45,$00
S00D5:
	.byte	$54,$48,$41,$54,$27,$53,$20,$54,$48,$45,$20,$53,$4F,$55,$4E,$44
	.byte	$20,$4F,$46,$20,$4C,$4F,$56,$45,$21,$00
S00FA:
	.byte	$59,$4F,$55,$52,$20,$53,$48,$49,$50,$27,$53,$20,$43,$4F,$52,$45
	.byte	$20,$45,$58,$50,$4C,$4F,$44,$45,$44,$00
S00CF:
	.byte	$4E,$4F,$20,$45,$53,$43,$41,$50,$45,$2E,$20,$4C,$4F,$54,$53,$20
	.byte	$4F,$46,$20,$53,$4C,$49,$4D,$45,$2E,$00
S00A6:
	.byte	$44,$4F,$4E,$27,$54,$20,$47,$45,$54,$20,$55,$53,$45,$44,$20,$54
	.byte	$4F,$20,$50,$52,$41,$49,$53,$45,$2E,$00
S0086:
	.byte	$42,$55,$54,$20,$49,$46,$20,$57,$45,$20,$44,$49,$45,$2C,$20,$49
	.byte	$27,$4D,$20,$54,$41,$4B,$49,$4E,$47,$00
S00FD:
	.byte	$54,$48,$45,$20,$45,$4E,$45,$4D,$59,$20,$43,$4C,$41,$49,$4D,$45
	.byte	$44,$20,$56,$49,$43,$54,$4F,$52,$59,$00
S00A8:
	.byte	$49,$27,$4D,$20,$2A,$51,$55,$49,$56,$45,$52,$49,$4E,$47,$2A,$20
	.byte	$49,$4E,$20,$50,$4C,$41,$43,$45,$53,$00
S0096:
	.byte	$4D,$59,$20,$42,$4C,$4F,$4F,$44,$27,$53,$20,$53,$54,$49,$4C,$4C
	.byte	$20,$48,$55,$4D,$4D,$49,$4E,$47,$2E,$00
S0002:
	.byte	$43,$41,$50,$54,$41,$49,$4E,$2C,$20,$57,$45,$20,$4E,$45,$45,$44
	.byte	$20,$41,$20,$48,$45,$52,$4F,$2C,$00
S0027:
	.byte	$2A,$4C,$45,$53,$53,$2A,$20,$53,$54,$55,$50,$49,$44,$20,$54,$48
	.byte	$49,$53,$20,$54,$49,$4D,$45,$2E,$00
S0073:
	.byte	$44,$4F,$4E,$27,$54,$20,$43,$4C,$45,$41,$4E,$20,$54,$48,$45,$20
	.byte	$43,$4F,$43,$4B,$50,$49,$54,$2E,$00
S0051:
	.byte	$54,$48,$45,$20,$42,$55,$42,$42,$4C,$45,$53,$20,$48,$41,$56,$45
	.byte	$20,$53,$50,$4F,$4B,$45,$4E,$2E,$00
S000E:
	.byte	$54,$41,$43,$54,$49,$43,$41,$4C,$20,$53,$59,$53,$54,$45,$4D,$53
	.byte	$20,$47,$52,$45,$45,$4E,$20,$2D,$00
S00BA:
	.byte	$41,$4E,$4F,$4D,$41,$4C,$4F,$55,$53,$20,$44,$41,$54,$41,$20,$44
	.byte	$45,$54,$45,$43,$54,$45,$44,$3A,$00
S0052:
	.byte	$54,$48,$45,$59,$20,$53,$41,$59,$20,$27,$50,$4F,$50,$20,$50,$4F
	.byte	$50,$20,$50,$4F,$50,$27,$2E,$00
S0032:
	.byte	$54,$48,$45,$20,$53,$41,$4D,$45,$20,$46,$4F,$52,$20,$54,$48,$45
	.byte	$20,$45,$4E,$45,$4D,$59,$2E,$00
S0015:
	.byte	$44,$4F,$4E,$27,$54,$20,$45,$58,$50,$45,$43,$54,$20,$4D,$45,$20
	.byte	$54,$4F,$20,$43,$4C,$41,$50,$00
S0099:
	.byte	$53,$4F,$4D,$45,$54,$48,$49,$4E,$47,$20,$45,$4C,$53,$45,$20,$54
	.byte	$4F,$20,$4B,$49,$4C,$4C,$2E,$00
S0030:
	.byte	$49,$27,$4D,$20,$53,$54,$49,$4C,$4C,$20,$49,$4E,$20,$4F,$4E,$45
	.byte	$20,$50,$49,$45,$43,$45,$2E,$00
S00F2:
	.byte	$54,$45,$4C,$4C,$20,$59,$4F,$55,$20,$48,$4F,$57,$20,$54,$48,$45
	.byte	$59,$20,$46,$45,$4C,$54,$2E,$00
S0018:
	.byte	$4E,$49,$43,$45,$20,$53,$48,$4F,$4F,$54,$49,$4E,$47,$2C,$20,$49
	.byte	$20,$47,$55,$45,$53,$53,$2E,$00
S00B6:
	.byte	$42,$55,$54,$20,$49,$46,$20,$59,$4F,$55,$20,$54,$45,$4C,$4C,$20
	.byte	$41,$4E,$59,$4F,$4E,$45,$00
S00E9:
	.byte	$47,$41,$4C,$41,$43,$54,$49,$43,$20,$43,$4F,$4D,$4D,$41,$4E,$44
	.byte	$20,$49,$53,$2E,$2E,$2E,$00
S004D:
	.byte	$4D,$4F,$52,$41,$4C,$45,$3A,$20,$4C,$41,$55,$47,$48,$41,$42,$4C
	.byte	$59,$20,$4C,$4F,$57,$2E,$00
S0087:
	.byte	$54,$48,$45,$20,$4D,$41,$49,$4E,$46,$52,$41,$4D,$45,$20,$57,$49
	.byte	$54,$48,$20,$4D,$45,$2E,$00
S0082:
	.byte	$53,$54,$41,$54,$49,$53,$54,$49,$43,$41,$4C,$20,$53,$55,$52,$56
	.byte	$49,$56,$41,$4C,$3A,$00
S005C:
	.byte	$54,$48,$45,$20,$53,$4D,$45,$4C,$4C,$20,$4F,$46,$20,$56,$49,$43
	.byte	$54,$4F,$52,$59,$2E,$00
S00AB:
	.byte	$54,$48,$41,$54,$20,$57,$41,$53,$20,$54,$48,$45,$20,$4A,$55,$49
	.byte	$43,$49,$45,$53,$54,$00
S0040:
	.byte	$2A,$53,$4C,$49,$50,$50,$45,$52,$59,$2A,$20,$57,$49,$54,$48,$20
	.byte	$4A,$4F,$59,$21,$00
S0063:
	.byte	$49,$4D,$50,$52,$4F,$56,$45,$4D,$45,$4E,$54,$20,$44,$45,$54,$45
	.byte	$43,$54,$45,$44,$00
S0089:
	.byte	$4F,$4F,$48,$2C,$20,$49,$27,$4D,$20,$2A,$54,$52,$45,$4D,$42,$4C
	.byte	$49,$4E,$47,$2A,$00
S00CD:
	.byte	$59,$4F,$55,$20,$41,$4E,$44,$20,$4D,$45,$2C,$20,$46,$4F,$52,$45
	.byte	$56,$45,$52,$21,$00
S0012:
	.byte	$42,$55,$42,$42,$4C,$45,$20,$4D,$4F,$44,$45,$20,$45,$4E,$47,$41
	.byte	$47,$45,$44,$21,$00
S000A:
	.byte	$49,$46,$20,$59,$4F,$55,$20,$47,$45,$54,$20,$4D,$45,$20,$4B,$49
	.byte	$4C,$4C,$45,$44,$00
S00A9:
	.byte	$49,$20,$44,$49,$44,$4E,$27,$54,$20,$4B,$4E,$4F,$57,$20,$49,$20
	.byte	$48,$41,$44,$21,$00
S0021:
	.byte	$59,$4F,$55,$27,$4C,$4C,$20,$44,$49,$45,$20,$54,$48,$49,$53,$20
	.byte	$54,$49,$4D,$45,$00
S00C9:
	.byte	$4F,$50,$54,$49,$4D,$41,$4C,$20,$50,$45,$52,$46,$4F,$52,$4D,$41
	.byte	$4E,$43,$45,$2E,$00
S003A:
	.byte	$49,$27,$56,$45,$20,$4C,$4F,$47,$47,$45,$44,$20,$54,$48,$45,$4D
	.byte	$20,$41,$4C,$4C,$00
S0031:
	.byte	$45,$56,$45,$4E,$20,$49,$46,$20,$49,$20,$43,$41,$4E,$27,$54,$20
	.byte	$53,$41,$59,$00
S004F:
	.byte	$42,$52,$45,$41,$4B,$20,$41,$4E,$59,$54,$48,$49,$4E,$47,$20,$45
	.byte	$4C,$53,$45,$00
S0034:
	.byte	$4F,$52,$20,$4D,$59,$20,$46,$41,$49,$54,$48,$20,$49,$4E,$20,$59
	.byte	$4F,$55,$2E,$00
S0046:
	.byte	$54,$4F,$20,$44,$49,$45,$20,$57,$49,$54,$48,$20,$48,$4F,$4E,$4F
	.byte	$55,$52,$2E,$00
S005E:
	.byte	$49,$46,$20,$54,$48,$45,$20,$46,$49,$4E,$41,$4C,$20,$42,$41,$54
	.byte	$54,$4C,$45,$00
S0098:
	.byte	$43,$4F,$4D,$45,$20,$4F,$4E,$2C,$20,$4C,$45,$54,$27,$53,$20,$46
	.byte	$49,$4E,$44,$00
S00F8:
	.byte	$47,$4C,$4F,$52,$49,$4F,$55,$53,$20,$4C,$41,$53,$45,$52,$46,$49
	.byte	$52,$45,$2E,$00
S00F5:
	.byte	$54,$48,$45,$20,$53,$54,$41,$52,$53,$20,$47,$52,$4F,$57,$20,$44
	.byte	$49,$4D,$2E,$00
S0079:
	.byte	$54,$48,$45,$20,$46,$49,$4E,$41,$4C,$20,$53,$4C,$41,$55,$47,$48
	.byte	$54,$45,$52,$00
S007C:
	.byte	$49,$4E,$54,$4F,$20,$54,$48,$45,$49,$52,$20,$43,$4F,$52,$50,$53
	.byte	$45,$53,$00
S003E:
	.byte	$53,$4F,$20,$4D,$41,$4E,$59,$20,$53,$50,$4C,$41,$54,$54,$45,$52
	.byte	$53,$21,$00
S006B:
	.byte	$50,$4F,$53,$53,$49,$42,$4C,$59,$20,$41,$20,$47,$4C,$49,$54,$43
	.byte	$48,$2E,$00
S006D:
	.byte	$44,$49,$44,$20,$59,$4F,$55,$20,$46,$45,$45,$4C,$20,$54,$48,$41
	.byte	$54,$3F,$00
S007B:
	.byte	$49,$27,$4C,$4C,$20,$43,$41,$52,$56,$45,$20,$4D,$59,$20,$4E,$41
	.byte	$4D,$45,$00
S0048:
	.byte	$4F,$52,$20,$54,$4F,$20,$53,$48,$4F,$4F,$54,$20,$46,$49,$52,$53
	.byte	$54,$2E,$00
S00C5:
	.byte	$52,$45,$4D,$41,$49,$4E,$20,$42,$59,$20,$4D,$59,$20,$53,$49,$44
	.byte	$45,$2E,$00
S00C1:
	.byte	$41,$54,$20,$4D,$41,$58,$49,$4D,$55,$4D,$20,$4F,$55,$54,$50,$55
	.byte	$54,$2E,$00
S0090:
	.byte	$53,$4F,$20,$46,$55,$4C,$4C,$20,$4F,$46,$20,$4A,$55,$49,$43,$45
	.byte	$2E,$00
S00E5:
	.byte	$59,$4F,$55,$20,$44,$49,$45,$44,$20,$53,$4F,$20,$46,$41,$53,$54
	.byte	$2C,$00
S00F4:
	.byte	$54,$48,$45,$20,$57,$41,$52,$20,$49,$53,$20,$4C,$4F,$53,$54,$20
	.byte	$26,$00
S0044:
	.byte	$4F,$4E,$45,$20,$4D,$4F,$52,$45,$20,$4D,$49,$53,$53,$49,$4F,$4E
	.byte	$2E,$00
S005F:
	.byte	$44,$49,$53,$41,$50,$50,$4F,$49,$4E,$54,$53,$20,$4D,$45,$2E,$2E
	.byte	$2E,$00
S00BE:
	.byte	$53,$54,$52,$4F,$4E,$47,$20,$46,$45,$45,$4C,$49,$4E,$47,$53,$2E
	.byte	$00
S0038:
	.byte	$4F,$50,$45,$52,$41,$54,$4F,$52,$20,$45,$52,$52,$4F,$52,$53,$2E
	.byte	$00
S00C0:
	.byte	$45,$4D,$4F,$54,$49,$4F,$4E,$41,$4C,$20,$43,$4F,$52,$45,$53,$2E
	.byte	$00
S0036:
	.byte	$4D,$49,$53,$53,$49,$4F,$4E,$20,$43,$4F,$4D,$50,$4C,$45,$54,$45
	.byte	$00
S00AE:
	.byte	$49,$27,$56,$45,$20,$4D,$41,$44,$45,$20,$41,$20,$4D,$45,$53,$53
	.byte	$00
S00D0	:=	S00F6+13
S0067:
	.byte	$4C,$45,$41,$52,$4E,$20,$53,$4F,$4D,$45,$54,$48,$49,$4E,$47,$3F
	.byte	$00
S0037:
	.byte	$44,$45,$53,$50,$49,$54,$45,$20,$4D,$55,$4C,$54,$49,$50,$4C,$45
	.byte	$00
S008A:
	.byte	$57,$49,$54,$48,$20,$45,$58,$43,$49,$54,$45,$4D,$45,$4E,$54,$21
	.byte	$00
S00B1	:=	S00F6+13
S009D:
	.byte	$57,$41,$53,$20,$55,$4E,$45,$58,$50,$45,$43,$54,$45,$44,$4C,$59
	.byte	$00
S0045:
	.byte	$4F,$4E,$45,$20,$4D,$4F,$52,$45,$20,$43,$48,$41,$4E,$43,$45,$00
S00D4	:=	S00F6+14
S0062	:=	S00F6+14
S0078	:=	S00F6+14
S00E3:
	.byte	$4D,$49,$53,$53,$49,$4F,$4E,$20,$46,$41,$49,$4C,$45,$44,$2E,$00
S00CE	:=	S00F6+15
S00C4	:=	S00F6+15
S002C:
	.byte	$53,$4F,$20,$4D,$55,$43,$48,$20,$53,$4C,$49,$4D,$45,$2E,$00
S0083	:=	S00F6+15
S0100	:=	S00F6+15
S00D3:
	.byte	$50,$4F,$50,$20,$50,$4F,$50,$20,$50,$4F,$50,$2E,$2E,$2E,$00
S00A5	:=	S00F6+15
S00B7	:=	S00F6+15
S00AC:
	.byte	$45,$58,$50,$4C,$4F,$53,$49,$4F,$4E,$20,$59,$45,$54,$21,$00
S00A1	:=	S00F6+15
S00EE	:=	S00F6+15
S00C8	:=	S00F6+15
S00DA	:=	S00F6+15
S009C	:=	S00F6+15
S00BD	:=	S00F6+15
S0059	:=	S00F6+16
S00A2:
	.byte	$50,$45,$52,$46,$4F,$52,$4D,$20,$57,$45,$4C,$4C,$3F,$00
S0020:
	.byte	$4F,$52,$20,$54,$48,$45,$59,$20,$54,$48,$49,$4E,$4B,$00
S00E6	:=	S00F6+16
S00B8:
	.byte	$49,$27,$4C,$4C,$20,$4B,$49,$4C,$4C,$20,$59,$4F,$55,$00
S0075:
	.byte	$49,$27,$4C,$4C,$20,$4C,$49,$43,$4B,$20,$49,$54,$2E,$00
S0066	:=	S00F6+16
S0026:
	.byte	$50,$4C,$45,$41,$53,$45,$20,$52,$45,$4D,$41,$49,$4E,$00
S005B	:=	S00F6+16
S0139:
	.byte	$4D,$52,$2E,$20,$42,$55,$42,$42,$4C,$45,$53,$3A,$00
S0121	:=	S0139+0
S011B	:=	S0139+0
S008C:
	.byte	$54,$48,$41,$54,$20,$53,$48,$49,$50,$2E,$2E,$2E,$00
S0133	:=	S0139+0
S0115	:=	S0139+0
S00BC:
	.byte	$46,$45,$45,$4C,$49,$4E,$47,$53,$2E,$2E,$2E,$20,$00
S0095	:=	S00F6+17
S003F:
	.byte	$54,$48,$45,$20,$46,$4C,$4F,$4F,$52,$20,$49,$53,$00
S012D	:=	S0139+0
S0109	:=	S0139+0
S010F	:=	S0139+0
S0127	:=	S0139+0
S00EB:
	.byte	$45,$4D,$42,$41,$52,$52,$41,$53,$53,$45,$44,$00
S006F:
	.byte	$54,$48,$41,$54,$20,$2A,$50,$4F,$50,$2A,$3F,$00
S00DB:
	.byte	$4E,$4F,$20,$50,$41,$52,$54,$4E,$45,$52,$2E,$00
S00FB:
	.byte	$49,$4E,$20,$53,$49,$4C,$45,$4E,$43,$45,$2E,$00
S00F7:
	.byte	$59,$4F,$55,$20,$44,$49,$45,$44,$20,$49,$4E,$00
S00ED:
	.byte	$53,$4F,$20,$43,$4C,$4F,$53,$45,$2E,$2E,$2E,$00
S001B:
	.byte	$57,$48,$45,$45,$45,$45,$45,$45,$45,$45,$21,$00
S0069:
	.byte	$55,$4E,$45,$58,$50,$45,$43,$54,$45,$44,$2E,$00
S0065:
	.byte	$44,$49,$44,$20,$59,$4F,$55,$2E,$2E,$2E,$00
S0077:
	.byte	$54,$48,$49,$53,$20,$49,$53,$20,$49,$54,$00
S004A:
	.byte	$59,$4F,$55,$52,$20,$43,$41,$4C,$4C,$2E,$00
S009E:
	.byte	$45,$46,$46,$45,$43,$54,$49,$56,$45,$2E,$00
S00FF:
	.byte	$59,$4F,$55,$52,$20,$43,$52,$45,$57,$3F,$00
S003C:
	.byte	$46,$4F,$52,$20,$4C,$41,$54,$45,$52,$2E,$00
S00A0	:=	S0065+0
S00EF:
	.byte	$41,$4E,$44,$20,$59,$45,$54,$2E,$2E,$2E,$00
S0135:
	.byte	$5A,$41,$52,$4E,$45,$4C,$4C,$41,$3A,$00
S00C3:
	.byte	$52,$45,$51,$55,$45,$53,$54,$3A,$20,$00
S0105	:=	S0135+0
S0061:
	.byte	$41,$4E,$41,$4C,$59,$53,$49,$53,$3A,$00
S012F	:=	S0135+0
S010B	:=	S0135+0
S00D9:
	.byte	$4E,$4F,$20,$4C,$4F,$56,$45,$2E,$20,$00
S0129	:=	S0135+0
S0111	:=	S0135+0
S0123	:=	S0135+0
S011D	:=	S0135+0
S0117	:=	S0135+0
S00DD:
	.byte	$4A,$55,$53,$54,$20,$59,$4F,$55,$2E,$00
S0084:
	.byte	$55,$4E,$4C,$49,$4B,$45,$4C,$59,$00
S008E:
	.byte	$53,$4F,$20,$42,$49,$47,$2E,$00
S011F:
	.byte	$4C,$55,$4D,$41,$2D,$36,$3A,$00
S0137	:=	S011F+0
S0113	:=	S011F+0
S0125	:=	S011F+0
S005A:
	.byte	$46,$4C,$41,$4D,$45,$53,$2E,$00
S00C7:
	.byte	$46,$4F,$52,$2E,$2E,$2E,$20,$00
S012B	:=	S011F+0
S010D	:=	S011F+0
S009B:
	.byte	$54,$48,$41,$54,$2E,$2E,$2E,$00
S0131	:=	S011F+0
S0107	:=	S011F+0
S0119	:=	S011F+0
S0058:
	.byte	$42,$4C,$4F,$4F,$44,$2E,$00
S0101:
	.byte	$47,$4F,$4E,$45,$2E,$00
S00A4:
	.byte	$4E,$4F,$2E,$00

; ---------------------------------------------------------------
; void __near__ show_typewriter (const struct $anon-struct-0001 *lines, unsigned char line_count)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_typewriter: near

.segment	"CODE"

;
; void show_typewriter(const DialogueLine* lines, unsigned char line_count) {
;
	jsr     pusha
;
; const char* current = lines[typewriter_line].text;
;
	ldx     #$00
	lda     _typewriter_line
	jsr     aslax2
	clc
	ldy     #$01
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	dey
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
;
; unsigned char x = lines[typewriter_line].x;
;
	ldx     #$00
	lda     _typewriter_line
	jsr     aslax2
	clc
	ldy     #$03
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	jsr     pusha
;
; unsigned char y = lines[typewriter_line].y;
;
	ldx     #$00
	lda     _typewriter_line
	jsr     aslax2
	clc
	ldy     #$04
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	jsr     pusha
;
; if (typewriter_line >= line_count) {
;
	lda     _typewriter_line
	ldy     #$04
	cmp     (sp),y
	bcc     L0009
;
; typewriter_ended = 1;
;
	lda     #$01
	sta     _typewriter_ended
;
; return;
;
	jmp     incsp7
;
; if (++typewriter_delay < 2) return; // Lower = faster typing
;
L0009:	inc     _typewriter_delay
	lda     _typewriter_delay
	cmp     #$02
	bcc     L0005
;
; typewriter_delay = 0;
;
	lda     #$00
	sta     _typewriter_delay
;
; if (current[typewriter_char] != '\0') {
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     _typewriter_char
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	beq     L000A
;
; one_vram_buffer(current[typewriter_char], NTADR_A(x + typewriter_char, y));
;
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     _typewriter_char
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldx     #$00
	iny
	lda     (sp),y
	clc
	adc     _typewriter_char
	bcc     L0008
	inx
L0008:	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; typewriter_char++;
;
	inc     _typewriter_char
;
; } else {
;
	jmp     incsp7
;
; typewriter_line++;
;
L000A:	inc     _typewriter_line
;
; typewriter_char = 0;
;
	sta     _typewriter_char
;
; }
;
L0005:	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ typewriter_reset (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_typewriter_reset: near

.segment	"CODE"

;
; typewriter_ended = 0;
;
	lda     #$00
	sta     _typewriter_ended
;
; typewriter_line = 0;
;
	sta     _typewriter_line
;
; typewriter_char = 0;
;
	sta     _typewriter_char
;
; typewriter_step = 0;
;
	sta     _typewriter_step
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ mission_begin_text (unsigned char level_num)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mission_begin_text: near

.segment	"CODE"

;
; void mission_begin_text(unsigned char level_num) {
;
	jsr     pusha
;
; if (level_num == 1) {
;
	ldy     #$00
	lda     (sp),y
	cmp     #$01
	jne     L001C
;
; if (selected_crewmate == 0) {
;
	lda     _selected_crewmate
	bne     L001A
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S0105)
	iny
	sta     (sp),y
	iny
	lda     #>(S0105)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_lv1_start, 4);
;
	lda     #<(_zarnella_lv1_start)
	ldx     #>(_zarnella_lv1_start)
	jsr     pushax
	lda     #$04
;
; else if (selected_crewmate == 1) {
;
	jmp     L0016
L001A:	lda     _selected_crewmate
	cmp     #$01
	bne     L0005
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S0107)
	iny
	sta     (sp),y
	iny
	lda     #>(S0107)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_lv1_start, 4);
;
	lda     #<(_luma_lv1_start)
	ldx     #>(_luma_lv1_start)
	jsr     pushax
	lda     #$04
;
; else {
;
	jmp     L0016
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L0005:	jsr     decsp3
	lda     #<(S0109)
	iny
	sta     (sp),y
	iny
	lda     #>(S0109)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_lv1_start, 3);
;
	lda     #<(_bubbles_lv1_start)
	ldx     #>(_bubbles_lv1_start)
	jsr     pushax
	lda     #$03
L0016:	jsr     _show_typewriter
;
; if (level_num == 2) {
;
	ldy     #$00
L001C:	lda     (sp),y
	cmp     #$02
	jne     L001F
;
; if (selected_crewmate == 0) {
;
	lda     _selected_crewmate
	bne     L001D
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S010B)
	iny
	sta     (sp),y
	iny
	lda     #>(S010B)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_lv2_start, 6);
;
	lda     #<(_zarnella_lv2_start)
	ldx     #>(_zarnella_lv2_start)
	jsr     pushax
	lda     #$06
;
; else if (selected_crewmate == 1) {
;
	jmp     L0017
L001D:	lda     _selected_crewmate
	cmp     #$01
	bne     L000A
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S010D)
	iny
	sta     (sp),y
	iny
	lda     #>(S010D)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_lv2_start, 6);
;
	lda     #<(_luma_lv2_start)
	ldx     #>(_luma_lv2_start)
	jsr     pushax
	lda     #$06
;
; else {
;
	jmp     L0017
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L000A:	jsr     decsp3
	lda     #<(S010F)
	iny
	sta     (sp),y
	iny
	lda     #>(S010F)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_lv2_start, 7);
;
	lda     #<(_bubbles_lv2_start)
	ldx     #>(_bubbles_lv2_start)
	jsr     pushax
	lda     #$07
L0017:	jsr     _show_typewriter
;
; if (level_num == 3) {
;
	ldy     #$00
L001F:	lda     (sp),y
	cmp     #$03
	bne     L0022
;
; if (selected_crewmate == 0) {
;
	lda     _selected_crewmate
	bne     L0020
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S0111)
	iny
	sta     (sp),y
	iny
	lda     #>(S0111)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_lv3_start, 8);
;
	lda     #<(_zarnella_lv3_start)
	ldx     #>(_zarnella_lv3_start)
	jsr     pushax
	lda     #$08
;
; else if (selected_crewmate == 1) {
;
	jmp     L0018
L0020:	lda     _selected_crewmate
	cmp     #$01
	bne     L000F
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S0113)
	iny
	sta     (sp),y
	iny
	lda     #>(S0113)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_lv3_start, 5);
;
	lda     #<(_luma_lv3_start)
	ldx     #>(_luma_lv3_start)
;
; else {
;
	jmp     L0025
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L000F:	jsr     decsp3
	lda     #<(S0115)
	iny
	sta     (sp),y
	iny
	lda     #>(S0115)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_lv3_start, 5);
;
	lda     #<(_bubbles_lv3_start)
	ldx     #>(_bubbles_lv3_start)
L0025:	jsr     pushax
	lda     #$05
L0018:	jsr     _show_typewriter
;
; if (level_num == 4) {
;
	ldy     #$00
L0022:	lda     (sp),y
	cmp     #$04
	jne     L0015
;
; if (selected_crewmate == 0) {
;
	lda     _selected_crewmate
	bne     L0023
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S0117)
	iny
	sta     (sp),y
	iny
	lda     #>(S0117)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_boss_start, 9);
;
	lda     #<(_zarnella_boss_start)
	ldx     #>(_zarnella_boss_start)
	jsr     pushax
	lda     #$09
;
; else if (selected_crewmate == 1) {
;
	jmp     L0019
L0023:	lda     _selected_crewmate
	cmp     #$01
	bne     L0014
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S0119)
	iny
	sta     (sp),y
	iny
	lda     #>(S0119)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_boss_start, 9);
;
	lda     #<(_luma_boss_start)
	ldx     #>(_luma_boss_start)
	jsr     pushax
	lda     #$09
;
; else {
;
	jmp     L0019
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L0014:	jsr     decsp3
	lda     #<(S011B)
	iny
	sta     (sp),y
	iny
	lda     #>(S011B)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_boss_start, 11);
;
	lda     #<(_bubbles_boss_start)
	ldx     #>(_bubbles_boss_start)
	jsr     pushax
	lda     #$0B
L0019:	jsr     _show_typewriter
;
; }
;
L0015:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ mission_end_text (unsigned char level_num)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mission_end_text: near

.segment	"CODE"

;
; void mission_end_text(unsigned char level_num) {
;
	jsr     pusha
;
; if (level_num == 1) {
;
	ldy     #$00
	lda     (sp),y
	cmp     #$01
	bne     L001C
;
; if (selected_crewmate == 0) {
;
	lda     _selected_crewmate
	bne     L001A
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S011D)
	iny
	sta     (sp),y
	iny
	lda     #>(S011D)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_lv1_end, 3);
;
	lda     #<(_zarnella_lv1_end)
	ldx     #>(_zarnella_lv1_end)
;
; else if (selected_crewmate == 1) {
;
	jmp     L0026
L001A:	lda     _selected_crewmate
	cmp     #$01
	bne     L0005
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S011F)
	iny
	sta     (sp),y
	iny
	lda     #>(S011F)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_lv1_end, 3);
;
	lda     #<(_luma_lv1_end)
	ldx     #>(_luma_lv1_end)
;
; else {
;
	jmp     L0026
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L0005:	jsr     decsp3
	lda     #<(S0121)
	iny
	sta     (sp),y
	iny
	lda     #>(S0121)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_lv1_end, 3);
;
	lda     #<(_bubbles_lv1_end)
	ldx     #>(_bubbles_lv1_end)
L0026:	jsr     pushax
	lda     #$03
	jsr     _show_typewriter
;
; if (level_num == 2) {
;
	ldy     #$00
L001C:	lda     (sp),y
	cmp     #$02
	bne     L001F
;
; if (selected_crewmate == 0) {
;
	lda     _selected_crewmate
	bne     L001D
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S0123)
	iny
	sta     (sp),y
	iny
	lda     #>(S0123)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_lv2_end, 6);
;
	lda     #<(_zarnella_lv2_end)
	ldx     #>(_zarnella_lv2_end)
;
; else if (selected_crewmate == 1) {
;
	jmp     L0027
L001D:	lda     _selected_crewmate
	cmp     #$01
	bne     L000A
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S0125)
	iny
	sta     (sp),y
	iny
	lda     #>(S0125)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_lv2_end, 8);
;
	lda     #<(_luma_lv2_end)
	ldx     #>(_luma_lv2_end)
	jsr     pushax
	lda     #$08
;
; else {
;
	jmp     L0017
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L000A:	jsr     decsp3
	lda     #<(S0127)
	iny
	sta     (sp),y
	iny
	lda     #>(S0127)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_lv2_end, 6);
;
	lda     #<(_bubbles_lv2_end)
	ldx     #>(_bubbles_lv2_end)
L0027:	jsr     pushax
	lda     #$06
L0017:	jsr     _show_typewriter
;
; if (level_num == 3) {
;
	ldy     #$00
L001F:	lda     (sp),y
	cmp     #$03
	jne     L0022
;
; if (selected_crewmate == 0) {
;
	lda     _selected_crewmate
	bne     L0020
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S0129)
	iny
	sta     (sp),y
	iny
	lda     #>(S0129)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_lv3_end, 11);
;
	lda     #<(_zarnella_lv3_end)
	ldx     #>(_zarnella_lv3_end)
	jsr     pushax
	lda     #$0B
;
; else if (selected_crewmate == 1) {
;
	jmp     L0018
L0020:	lda     _selected_crewmate
	cmp     #$01
	bne     L000F
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S012B)
	iny
	sta     (sp),y
	iny
	lda     #>(S012B)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_lv3_end, 12);
;
	lda     #<(_luma_lv3_end)
	ldx     #>(_luma_lv3_end)
	jsr     pushax
	lda     #$0C
;
; else {
;
	jmp     L0018
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L000F:	jsr     decsp3
	lda     #<(S012D)
	iny
	sta     (sp),y
	iny
	lda     #>(S012D)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_lv3_end, 10);
;
	lda     #<(_bubbles_lv3_end)
	ldx     #>(_bubbles_lv3_end)
	jsr     pushax
	lda     #$0A
L0018:	jsr     _show_typewriter
;
; if (level_num == 4) {
;
	ldy     #$00
L0022:	lda     (sp),y
	cmp     #$04
	jne     L0015
;
; if (selected_crewmate == 0) {
;
	lda     _selected_crewmate
	bne     L0023
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S012F)
	iny
	sta     (sp),y
	iny
	lda     #>(S012F)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_boss_end, 7);
;
	lda     #<(_zarnella_boss_end)
	ldx     #>(_zarnella_boss_end)
	jsr     pushax
	lda     #$07
;
; else if (selected_crewmate == 1) {
;
	jmp     L0019
L0023:	lda     _selected_crewmate
	cmp     #$01
	bne     L0014
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S0131)
	iny
	sta     (sp),y
	iny
	lda     #>(S0131)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_boss_end, 13);
;
	lda     #<(_luma_boss_end)
	ldx     #>(_luma_boss_end)
	jsr     pushax
	lda     #$0D
;
; else {
;
	jmp     L0019
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L0014:	jsr     decsp3
	lda     #<(S0133)
	iny
	sta     (sp),y
	iny
	lda     #>(S0133)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_boss_end, 8);
;
	lda     #<(_bubbles_boss_end)
	ldx     #>(_bubbles_boss_end)
	jsr     pushax
	lda     #$08
L0019:	jsr     _show_typewriter
;
; }
;
L0015:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ show_romance_ending (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_romance_ending: near

.segment	"CODE"

;
; unsigned char winner = get_romance_winner();
;
	jsr     _get_romance_winner
	jsr     pusha
;
; if (total_romance_score >= 3000) {
;
	lda     _total_romance_score
	cmp     #$B8
	lda     _total_romance_score+1
	sbc     #$0B
	bcc     L0002
;
; if (winner == 0) { // Zarnella
;
	ldy     #$00
	lda     (sp),y
	bne     L000A
;
; WRITE("ZARNELLA:", 12, 6);
;
	jsr     decsp3
	lda     #<(S0135)
	iny
	sta     (sp),y
	iny
	lda     #>(S0135)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CC
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(zarnella_romance, 10);
;
	lda     #<(_zarnella_romance)
	ldx     #>(_zarnella_romance)
	jsr     pushax
	lda     #$0A
;
; } else if (winner == 1) { // Luma-6
;
	jmp     L0008
L000A:	lda     (sp),y
	cmp     #$01
	bne     L0005
;
; WRITE("LUMA-6:", 13, 6);
;
	jsr     decsp3
	lda     #<(S0137)
	iny
	sta     (sp),y
	iny
	lda     #>(S0137)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CD
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(luma_romance, 17);
;
	lda     #<(_luma_romance)
	ldx     #>(_luma_romance)
	jsr     pushax
	lda     #$11
;
; } else { // Mr. Bubbles
;
	jmp     L0008
;
; WRITE("MR. BUBBLES:", 10, 6);
;
L0005:	jsr     decsp3
	lda     #<(S0139)
	iny
	sta     (sp),y
	iny
	lda     #>(S0139)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$CA
	jsr     _multi_vram_buffer_horz
;
; show_typewriter(bubbles_romance, 12);
;
	lda     #<(_bubbles_romance)
	ldx     #>(_bubbles_romance)
;
; } else {
;
	jmp     L000C
;
; show_typewriter(lonely_ending, 12);
;
L0002:	lda     #<(_lonely_ending)
	ldx     #>(_lonely_ending)
L000C:	jsr     pushax
	lda     #$0C
L0008:	jsr     _show_typewriter
;
; player_score = total_romance_score;
;
	lda     _total_romance_score+1
	sta     _player_score+1
	lda     _total_romance_score
	sta     _player_score
;
; update_score_string();
;
	jsr     _update_score_string
;
; WRITE(score_string, 10, 24);
;
	jsr     decsp3
	lda     #<(_score_string)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_score_string)
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	ldx     #$23
	lda     #$0A
	jsr     _multi_vram_buffer_horz
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ show_game_over_screen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_game_over_screen: near

.segment	"CODE"

;
; if (current_level <= 2) {
;
	lda     _current_level
	cmp     #$03
	bcs     L0007
;
; show_typewriter(gameover_early, 10);
;
	lda     #<(_gameover_early)
	ldx     #>(_gameover_early)
	jsr     pushax
	lda     #$0A
;
; } else if (current_level == 3) {
;
	jmp     _show_typewriter
L0007:	lda     _current_level
	cmp     #$03
	bne     L0004
;
; show_typewriter(gameover_mid, 10);
;
	lda     #<(_gameover_mid)
	ldx     #>(_gameover_mid)
	jsr     pushax
	lda     #$0A
;
; } else {
;
	jmp     _show_typewriter
;
; show_typewriter(gameover_late, 14);
;
L0004:	lda     #<(_gameover_late)
	ldx     #>(_gameover_late)
	jsr     pushax
	lda     #$0E
	jmp     _show_typewriter

.endproc

