;
; File generated by cc65 v 2.19 - Git 065b0d7
;
	.fopt		compiler,"cc65 v 2.19 - Git 065b0d7"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_oam_meta_spr
	.import		_rand8
	.export		_enemy_x
	.export		_enemy_y
	.export		_enemy_active
	.export		_enemy_frozen
	.export		_spawn_enemies
	.export		_update_enemies
	.export		_clear_all_enemies
	.import		_i
	.import		_frame_count
	.import		_enemy_sprite

.segment	"BSS"

_enemy_x:
	.res	6,$00
_enemy_y:
	.res	6,$00
_enemy_active:
	.res	6,$00
_enemy_frozen:
	.res	6,$00

; ---------------------------------------------------------------
; void __near__ spawn_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spawn_enemies: near

.segment	"CODE"

;
; if ((frame_count % 60) == 0) {
;
	lda     _frame_count
	jsr     pusha0
	lda     #$3C
	jsr     tosumoda0
	cpx     #$00
	bne     L0005
	cmp     #$00
	bne     L0005
;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
	sta     _i
L000E:	lda     _i
	cmp     #$06
	bcs     L0005
;
; if (!enemy_active[i]) {
;
	ldy     _i
	lda     _enemy_active,y
	bne     L000F
;
; enemy_active[i] = 1;
;
	ldy     _i
	lda     #$01
	sta     _enemy_active,y
;
; enemy_x[i] = 240;
;
	ldy     _i
	lda     #$F0
	sta     _enemy_x,y
;
; enemy_y[i] = PLAYFIELD_TOP + (rand8() % (PLAYFIELD_BOTTOM - PLAYFIELD_TOP));
;
	lda     #<(_enemy_y)
	ldx     #>(_enemy_y)
	clc
	adc     _i
	bcc     L000C
	inx
L000C:	jsr     pushax
	jsr     _rand8
	jsr     pushax
	lda     #$90
	jsr     tosumoda0
	clc
	adc     #$30
	ldy     #$00
	jmp     staspidx
;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
L000F:	inc     _i
	jmp     L000E
;
; }
;
L0005:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_enemies: near

.segment	"CODE"

;
; if (frame_count % 2 == 0) {
;
	lda     _frame_count
	and     #$01
	bne     L0020
;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
	sta     _i
L001B:	lda     _i
	cmp     #$06
	bcs     L0020
;
; if (enemy_active[i] && !enemy_frozen[i]) {
;
	ldy     _i
	lda     _enemy_active,y
	beq     L001F
	ldy     _i
	lda     _enemy_frozen,y
	bne     L001F
;
; if (enemy_x[i] <= ENEMY_LEFT_LIMIT) {
;
	ldy     _i
	lda     _enemy_x,y
	cmp     #$09
	bcs     L000E
;
; enemy_active[i] = 0;
;
	ldy     _i
	lda     #$00
	sta     _enemy_active,y
;
; } else {
;
	jmp     L001F
;
; enemy_x[i] -= 1;
;
L000E:	lda     #<(_enemy_x)
	ldx     #>(_enemy_x)
	clc
	adc     _i
	bcc     L0012
	inx
L0012:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sec
	sbc     #$01
	sta     (ptr1),y
;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
L001F:	inc     _i
	jmp     L001B
;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
L0020:	lda     #$00
	sta     _i
L0021:	lda     _i
	cmp     #$06
	bcs     L0014
;
; if (enemy_active[i]) {
;
	ldy     _i
	lda     _enemy_active,y
	beq     L0022
;
; oam_meta_spr(enemy_x[i], enemy_y[i], enemy_sprite);
;
	jsr     decsp2
	ldy     _i
	lda     _enemy_x,y
	ldy     #$01
	sta     (sp),y
	ldy     _i
	lda     _enemy_y,y
	ldy     #$00
	sta     (sp),y
	lda     #<(_enemy_sprite)
	ldx     #>(_enemy_sprite)
	jsr     _oam_meta_spr
;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
L0022:	inc     _i
	jmp     L0021
;
; }
;
L0014:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ clear_all_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_all_enemies: near

.segment	"CODE"

;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
	lda     #$00
	sta     _i
L0008:	lda     _i
	cmp     #$06
	bcs     L0003
;
; enemy_active[i] = 0;
;
	ldy     _i
	lda     #$00
	sta     _enemy_active,y
;
; enemy_frozen[i] = 0;
;
	ldy     _i
	sta     _enemy_frozen,y
;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
	inc     _i
	jmp     L0008
;
; }
;
L0003:	rts

.endproc

