;
; File generated by cc65 v 2.19 - Git 065b0d7
;
	.fopt		compiler,"cc65 v 2.19 - Git 065b0d7"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_game_state
	.export		_current_level
	.export		_i
	.export		_j
	.export		_briefing_started
	.export		_selected_crewmate
	.export		_previous_crewmate
	.export		_shmup_screen_drawn
	.export		_shmup_started
	.export		_dialogue_shown
	.export		_ending_shown
	.export		_ability_ready
	.export		_hp_string
	.export		_frame_count
	.export		_ability_cooldown_timer
	.export		_pad1
	.export		_pad1_old
	.export		_player_invincible
	.export		_invincibility_timer
	.export		_zarnella_laser_timer
	.export		_player_x
	.export		_player_y
	.export		_player_health
	.export		_bullet_x
	.export		_bullet_y
	.export		_bullet_active
	.export		_bullets
	.export		_boss_active
	.export		_boss_health
	.export		_boss_x
	.export		_boss_y
	.export		_boss_attack_mode
	.export		_boss_fire_timer
	.export		_boss_bullet_x
	.export		_boss_bullet_y
	.export		_boss_bullet_active
	.export		_freeze_timer
	.export		_player_score
	.export		_score_string
	.export		_shmup_timer
	.export		_timer_string
	.export		_typewriter_step
	.export		_typewriter_line
	.export		_typewriter_ended
	.export		_zarnella_picks
	.export		_luma_picks
	.export		_bubbles_picks
	.export		_total_romance_score
	.export		_bullet_box
	.export		_enemy_box
	.export		_enemy_type
	.export		_enemy_health
	.export		_tens
	.export		_ones
	.export		_player_sprite
	.export		_bullet_sprite
	.export		_special_bullet_sprite
	.export		_enemy_sprite_basic
	.export		_enemy_sprite_fast
	.export		_enemy_sprite_tough
	.export		_enemy_sprites
	.export		_boss_bullet_sprite
	.export		_boss_sprite
	.export		_palette
	.export		_tough_debris_1
	.export		_tough_debris_2
	.export		_tough_debris_3
	.export		_tough_debris_4
	.export		_tough_debris_5
	.export		_tough_debris_6
	.export		_tough_debris_7
	.export		_tough_debris_8
	.export		_tough_debris_9
	.export		_tough_debris_variants
	.export		_enemy_variant

.segment	"DATA"

_game_state:
	.byte	$00
_current_level:
	.byte	$01
_i:
	.byte	$00
_j:
	.byte	$00
_briefing_started:
	.byte	$00
_selected_crewmate:
	.byte	$00
_previous_crewmate:
	.byte	$00
_shmup_screen_drawn:
	.byte	$00
_shmup_started:
	.byte	$00
_dialogue_shown:
	.byte	$00
_ending_shown:
	.byte	$00
_ability_ready:
	.byte	$01
_hp_string:
	.byte	$48,$50,$3A,$20,$33,$00
_frame_count:
	.byte	$00
_ability_cooldown_timer:
	.word	$0000
_player_invincible:
	.byte	$00
_invincibility_timer:
	.byte	$00
_zarnella_laser_timer:
	.byte	$00
_player_x:
	.byte	$20
_player_y:
	.byte	$78
_player_health:
	.byte	$03
_boss_active:
	.byte	$00
_boss_health:
	.byte	$14
_boss_x:
	.byte	$D8
_boss_y:
	.byte	$64
_boss_attack_mode:
	.byte	$00
_boss_fire_timer:
	.byte	$00
_freeze_timer:
	.word	$0000
_player_score:
	.word	$0000
_score_string:
	.byte	$53,$43,$4F,$52,$45,$3A,$20,$30,$30,$30,$30,$30,$00
_shmup_timer:
	.word	$1518
_timer_string:
	.byte	$54,$49,$4D,$45,$52,$3A,$20,$39,$30,$00
_typewriter_step:
	.byte	$00
_typewriter_line:
	.byte	$00
_typewriter_ended:
	.byte	$00
_zarnella_picks:
	.byte	$00
_luma_picks:
	.byte	$00
_bubbles_picks:
	.byte	$00
_total_romance_score:
	.word	$0000
_tens:
	.byte	$00
_ones:
	.byte	$00
_enemy_sprites:
	.addr	_enemy_sprite_basic
	.addr	_enemy_sprite_fast
	.addr	_enemy_sprite_tough
_tough_debris_variants:
	.addr	_tough_debris_1
	.addr	_tough_debris_2
	.addr	_tough_debris_3
	.addr	_tough_debris_4
	.addr	_tough_debris_5
	.addr	_tough_debris_6
	.addr	_tough_debris_7
	.addr	_tough_debris_8
	.addr	_tough_debris_9

.segment	"RODATA"

_player_sprite:
	.byte	$00
	.byte	$00
	.byte	$96
	.byte	$01
	.byte	$80
_bullet_sprite:
	.byte	$00
	.byte	$00
	.byte	$2D
	.byte	$00
	.byte	$80
_special_bullet_sprite:
	.byte	$00
	.byte	$00
	.byte	$3E
	.byte	$00
	.byte	$80
_enemy_sprite_basic:
	.byte	$00
	.byte	$00
	.byte	$B7
	.byte	$03
	.byte	$80
_enemy_sprite_fast:
	.byte	$00
	.byte	$00
	.byte	$98
	.byte	$02
	.byte	$80
_enemy_sprite_tough:
	.byte	$00
	.byte	$00
	.byte	$5B
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$5C
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$5B
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$5C
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$5B
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$5C
	.byte	$00
	.byte	$80
_boss_bullet_sprite:
	.byte	$00
	.byte	$00
	.byte	$7E
	.byte	$00
	.byte	$80
_boss_sprite:
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$4F
	.byte	$00
	.byte	$10
	.byte	$00
	.byte	$53
	.byte	$00
	.byte	$18
	.byte	$00
	.byte	$53
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$42
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$4F
	.byte	$00
	.byte	$10
	.byte	$08
	.byte	$53
	.byte	$00
	.byte	$18
	.byte	$08
	.byte	$53
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$42
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$4F
	.byte	$00
	.byte	$10
	.byte	$10
	.byte	$53
	.byte	$00
	.byte	$18
	.byte	$10
	.byte	$53
	.byte	$00
	.byte	$00
	.byte	$18
	.byte	$42
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$4F
	.byte	$00
	.byte	$10
	.byte	$18
	.byte	$53
	.byte	$00
	.byte	$18
	.byte	$18
	.byte	$53
	.byte	$00
	.byte	$00
	.byte	$20
	.byte	$42
	.byte	$00
	.byte	$08
	.byte	$20
	.byte	$4F
	.byte	$00
	.byte	$10
	.byte	$20
	.byte	$53
	.byte	$00
	.byte	$18
	.byte	$20
	.byte	$53
	.byte	$00
	.byte	$80
_palette:
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$0F
	.byte	$11
	.byte	$21
	.byte	$38
	.byte	$0F
	.byte	$05
	.byte	$15
	.byte	$25
	.byte	$0F
	.byte	$27
	.byte	$1A
	.byte	$29
_tough_debris_1:
	.byte	$00
	.byte	$00
	.byte	$92
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$A3
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$B4
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$94
	.byte	$01
	.byte	$00
	.byte	$10
	.byte	$A2
	.byte	$01
	.byte	$08
	.byte	$10
	.byte	$B2
	.byte	$01
	.byte	$80
_tough_debris_2:
	.byte	$00
	.byte	$00
	.byte	$A3
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$93
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$B3
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$92
	.byte	$01
	.byte	$00
	.byte	$10
	.byte	$A4
	.byte	$01
	.byte	$08
	.byte	$10
	.byte	$B4
	.byte	$01
	.byte	$80
_tough_debris_3:
	.byte	$00
	.byte	$00
	.byte	$B2
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$A2
	.byte	$01
	.byte	$00
	.byte	$08
	.byte	$92
	.byte	$01
	.byte	$08
	.byte	$08
	.byte	$94
	.byte	$01
	.byte	$00
	.byte	$10
	.byte	$B4
	.byte	$01
	.byte	$08
	.byte	$10
	.byte	$A3
	.byte	$01
	.byte	$80
_tough_debris_4:
	.byte	$00
	.byte	$00
	.byte	$94
	.byte	$02
	.byte	$08
	.byte	$00
	.byte	$B3
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$A2
	.byte	$02
	.byte	$08
	.byte	$08
	.byte	$B2
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$93
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$A4
	.byte	$02
	.byte	$80
_tough_debris_5:
	.byte	$00
	.byte	$00
	.byte	$B4
	.byte	$02
	.byte	$08
	.byte	$00
	.byte	$A3
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$92
	.byte	$02
	.byte	$08
	.byte	$08
	.byte	$93
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$A2
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$B2
	.byte	$02
	.byte	$80
_tough_debris_6:
	.byte	$00
	.byte	$00
	.byte	$92
	.byte	$02
	.byte	$08
	.byte	$00
	.byte	$A2
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$B3
	.byte	$02
	.byte	$08
	.byte	$08
	.byte	$A4
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$93
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$B4
	.byte	$02
	.byte	$80
_tough_debris_7:
	.byte	$00
	.byte	$00
	.byte	$A3
	.byte	$03
	.byte	$08
	.byte	$00
	.byte	$B4
	.byte	$03
	.byte	$00
	.byte	$08
	.byte	$A2
	.byte	$03
	.byte	$08
	.byte	$08
	.byte	$94
	.byte	$03
	.byte	$00
	.byte	$10
	.byte	$93
	.byte	$03
	.byte	$08
	.byte	$10
	.byte	$B2
	.byte	$03
	.byte	$80
_tough_debris_8:
	.byte	$00
	.byte	$00
	.byte	$B2
	.byte	$03
	.byte	$08
	.byte	$00
	.byte	$94
	.byte	$03
	.byte	$00
	.byte	$08
	.byte	$A4
	.byte	$03
	.byte	$08
	.byte	$08
	.byte	$B3
	.byte	$03
	.byte	$00
	.byte	$10
	.byte	$92
	.byte	$03
	.byte	$08
	.byte	$10
	.byte	$A3
	.byte	$03
	.byte	$80
_tough_debris_9:
	.byte	$00
	.byte	$00
	.byte	$A4
	.byte	$03
	.byte	$08
	.byte	$00
	.byte	$92
	.byte	$03
	.byte	$00
	.byte	$08
	.byte	$93
	.byte	$03
	.byte	$08
	.byte	$08
	.byte	$B4
	.byte	$03
	.byte	$00
	.byte	$10
	.byte	$A2
	.byte	$03
	.byte	$08
	.byte	$10
	.byte	$B3
	.byte	$03
	.byte	$80

.segment	"BSS"

_pad1:
	.res	1,$00
_pad1_old:
	.res	1,$00
_bullet_x:
	.res	3,$00
_bullet_y:
	.res	3,$00
_bullet_active:
	.res	3,$00
_bullets:
	.res	15,$00
_boss_bullet_x:
	.res	10,$00
_boss_bullet_y:
	.res	10,$00
_boss_bullet_active:
	.res	10,$00
_bullet_box:
	.res	4,$00
_enemy_box:
	.res	4,$00
_enemy_type:
	.res	6,$00
_enemy_health:
	.res	6,$00
_enemy_variant:
	.res	6,$00

