;
; File generated by cc65 v 2.19 - Git 065b0d7
;
	.fopt		compiler,"cc65 v 2.19 - Git 065b0d7"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_draw_player
	.export		_handle_shmup_input
	.export		_check_player_hit
	.import		_oam_meta_spr
	.import		_i
	.import		_pad1
	.import		_player_invincible
	.import		_player_x
	.import		_player_y
	.import		_player_health
	.import		_player_sprite
	.import		_enemy_x
	.import		_enemy_y
	.import		_enemy_active
	.import		_on_player_death

; ---------------------------------------------------------------
; void __near__ draw_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_player: near

.segment	"CODE"

;
; const unsigned char* sprite = player_sprite;
;
	lda     #<(_player_sprite)
	ldx     #>(_player_sprite)
	jsr     pushax
;
; for (i = 0; i < 5; ++i) {
;
	lda     #$00
	sta     _i
L000A:	lda     _i
	cmp     #$05
	bcs     L0003
;
; temp_sprite[i] = player_sprite[i];
;
	lda     #<(M0001)
	ldx     #>(M0001)
	clc
	adc     _i
	bcc     L0006
	inx
L0006:	sta     ptr1
	stx     ptr1+1
	ldy     _i
	lda     _player_sprite,y
	ldy     #$00
	sta     (ptr1),y
;
; for (i = 0; i < 5; ++i) {
;
	inc     _i
	jmp     L000A
;
; temp_sprite[3] = player_invincible ? 1 : 0;
;
L0003:	lda     _player_invincible
	beq     L000C
	lda     #$01
L000C:	sta     M0001+3
;
; oam_meta_spr(player_x, player_y, temp_sprite);
;
	jsr     decsp2
	lda     _player_x
	ldy     #$01
	sta     (sp),y
	lda     _player_y
	dey
	sta     (sp),y
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     _oam_meta_spr
;
; }
;
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	5,$00

.endproc

; ---------------------------------------------------------------
; void __near__ handle_shmup_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_handle_shmup_input: near

.segment	"CODE"

;
; if (pad1 & PAD_LEFT && player_x > 8) player_x--;
;
	lda     _pad1
	and     #$02
	beq     L0015
	lda     _player_x
	cmp     #$09
	bcc     L0015
	dec     _player_x
;
; if (pad1 & PAD_RIGHT && player_x < 40) player_x++;
;
L0015:	lda     _pad1
	and     #$01
	beq     L0019
	lda     _player_x
	cmp     #$28
	bcs     L0019
	inc     _player_x
;
; if (pad1 & PAD_UP && player_y > PLAYFIELD_TOP) player_y--;
;
L0019:	lda     _pad1
	and     #$08
	beq     L001D
	lda     _player_y
	cmp     #$31
	bcc     L001D
	dec     _player_y
;
; if (pad1 & PAD_DOWN && player_y < PLAYFIELD_BOTTOM) player_y++;
;
L001D:	lda     _pad1
	and     #$04
	beq     L001F
	lda     _player_y
	cmp     #$C0
	bcc     L0020
L001F:	rts
L0020:	inc     _player_y
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ check_player_hit (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_check_player_hit: near

.segment	"CODE"

;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
	lda     #$00
	sta     _i
L0024:	lda     _i
	cmp     #$06
	bcc     L0031
;
; }
;
	rts
;
; if (enemy_active[i] && enemy_x[i] < 44) {
;
L0031:	ldy     _i
	lda     _enemy_active,y
	jeq     L002C
	ldy     _i
	lda     _enemy_x,y
	cmp     #$2C
	jcs     L002C
;
; if ((player_x > enemy_x[i] ? player_x - enemy_x[i] : enemy_x[i] - player_x) < 6 &&
;
	lda     _player_x
	ldy     _i
	cmp     _enemy_x,y
	bcc     L000E
	beq     L000E
	lda     _player_x
	sec
	ldy     _i
	sbc     _enemy_x,y
	jmp     L002F
L000E:	ldy     _i
	lda     _enemy_x,y
	sec
	sbc     _player_x
L002F:	ldx     #$00
	bcs     L0010
	dex
L0010:	cmp     #$06
	txa
	sbc     #$00
	bvc     L0012
	eor     #$80
L0012:	bpl     L002C
;
; (player_y > enemy_y[i] ? player_y - enemy_y[i] : enemy_y[i] - player_y) < 6) {
;
	lda     _player_y
	ldy     _i
	cmp     _enemy_y,y
	bcc     L0015
	beq     L0015
	lda     _player_y
	sec
	ldy     _i
	sbc     _enemy_y,y
	jmp     L0030
L0015:	ldy     _i
	lda     _enemy_y,y
	sec
	sbc     _player_y
L0030:	ldx     #$00
	bcs     L0017
	dex
L0017:	cmp     #$06
	txa
	sbc     #$00
	bvc     L0019
	eor     #$80
L0019:	bpl     L002C
;
; enemy_active[i] = 0; // enemy dies on impact
;
	ldy     _i
	lda     #$00
	sta     _enemy_active,y
;
; if (!player_invincible) {
;
	lda     _player_invincible
	bne     L002B
;
; if (player_health > 0) {
;
	lda     _player_health
	beq     L002B
;
; player_health--;
;
	dec     _player_health
;
; if (player_health == 0) {
;
L002B:	lda     _player_health
	bne     L0003
;
; on_player_death();
;
	jmp     _on_player_death
;
; for (i = 0; i < MAX_ENEMIES; ++i) {
;
L002C:	inc     _i
	jmp     L0024
;
; }
;
L0003:	rts

.endproc

